name: Deploy Trading Bot

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Add SSH key to agent
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.SERVER_SSH_KEY }}" | tr -d '\r' | ssh-add -

    - name: Deploy to DigitalOcean
      env:
        HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        ssh -v root@$HOST 'echo "SSH connection successful"'
        scp -v -r ./* root@$HOST:/root/
        ssh root@$HOST 'bash -s' < deploy_bot.sh
        ssh root@$HOST 'systemctl restart trading-bot'